baseURL = "https://ender.gallery/"
languageCode = "en-us"
title = "Ender Gallery"
theme = "endertheme"
[params]
  sitename = "Ender Gallery"
  twitter = "@isthisanart_"
  description = "Ender Gallery is an exhibition space and artist residency that exists inside the game Minecraft."
[markup.goldmark.renderer]
  unsafe= true