name = "onlinegrimoire"
license = "MIT"
licenselink = "https://github.com/ana0/blog-theme/blob/master/LICENSE.md"
description = "Online grimoire"
homepage = "https://github.com/ana0/blog-themes"
tags = ["blog"]
features = ["blog"]
min_version = "0.30.2"

[author]
  name = "Sarah Friend"
  homepage = "https://github.com/ana0/blog-theme/"